version: '3.5'

services:
  mssql-server:
    restart: always
    #environment:
        #ACCEPT_EULA: 'Y'
        #SA_PASSWORD: Tarek123
        #MSSQL_PID: Express
    env_file:
        - mssql-server.env
    ports:
      - 1433:1433
    image: mcr.microsoft.com/mssql/server:2017-CU20-ubuntu-16.04
    volumes:
      # - mssql-server-volume:/var/lib/mysql
      - sql1data:/var/opt/mssql
  mvc-app:
    # build: .
    env_file: 
      - crud-mvc-app.env
    image: titario/crudmvcapp:2.0
    restart: always
    ports:
      - "4443:80"
    depends_on:
      - mssql-server

volumes:
  sql1data: